# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ReceiptItem(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, item_name: str=None, price: float=None):  # noqa: E501
        """ReceiptItem - a model defined in Swagger

        :param item_name: The item_name of this ReceiptItem.  # noqa: E501
        :type item_name: str
        :param price: The price of this ReceiptItem.  # noqa: E501
        :type price: float
        """
        self.swagger_types = {
            'item_name': str,
            'price': float
        }

        self.attribute_map = {
            'item_name': 'itemName',
            'price': 'price'
        }

        self._item_name = item_name
        self._price = price

    @classmethod
    def from_dict(cls, dikt) -> 'ReceiptItem':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ReceiptItem of this ReceiptItem.  # noqa: E501
        :rtype: ReceiptItem
        """
        return util.deserialize_model(dikt, cls)

    @property
    def item_name(self) -> str:
        """Gets the item_name of this ReceiptItem.


        :return: The item_name of this ReceiptItem.
        :rtype: str
        """
        return self._item_name

    @item_name.setter
    def item_name(self, item_name: str):
        """Sets the item_name of this ReceiptItem.


        :param item_name: The item_name of this ReceiptItem.
        :type item_name: str
        """

        self._item_name = item_name

    @property
    def price(self) -> float:
        """Gets the price of this ReceiptItem.


        :return: The price of this ReceiptItem.
        :rtype: float
        """
        return self._price

    @price.setter
    def price(self, price: float):
        """Sets the price of this ReceiptItem.


        :param price: The price of this ReceiptItem.
        :type price: float
        """

        self._price = price
