# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class User(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, balance: float=None):  # noqa: E501
        """User - a model defined in Swagger

        :param balance: The balance of this User.  # noqa: E501
        :type balance: float
        """
        self.swagger_types = {
            'balance': float
        }

        self.attribute_map = {
            'balance': 'balance'
        }

        self._balance = balance

    @classmethod
    def from_dict(cls, dikt) -> 'User':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The User of this User.  # noqa: E501
        :rtype: User
        """
        return util.deserialize_model(dikt, cls)

    @property
    def balance(self) -> float:
        """Gets the balance of this User.


        :return: The balance of this User.
        :rtype: float
        """
        return self._balance

    @balance.setter
    def balance(self, balance: float):
        """Sets the balance of this User.


        :param balance: The balance of this User.
        :type balance: float
        """

        self._balance = balance
